<template>
  <div id="specs">
    <div class="view_container">
      <div class="view_info">
        <h2 class="view_title">Specs</h2>
        <p class="view_description">Technical Specifications</p>
      </div>
      <div class="doc_content">
        <div class="doc_pic">
          <img src="../assets/img/logo_mb_blue.png" alt="book.title" />
        </div>
        <div class="doc_info">
          <div class="doc_info_text">
            <p>
              The project is mainly based on Node.js (server-side) and Vue.js
              (client-side). Some components have been defined to facilitate the
              design and navigation between the views, supported by the
              installation of vue-router. 'App' is the main component, in which
              'Header' (which contains the navigation menu) and 'Footer' (with a
              simple link to the author's LinkedIn profile) are called up.
            </p>

            <p>
              In the middle, the 'views', that are alternated avoiding the page
              refresh: 'BookStore', the main one, in which, through Axios, all
              the books included in the 'database' are collected and shown.
              'About' contains general information regarding the project and
              this view, 'Specs', illustrates more technical specifications.
            </p>
            <p>
              Sass has been installed to build the general stylesheet, based on
              specific partials for each type of formatting (variables, common
              properties, mixins, media queries, effects, etc.). In
              'BookDetails', clicking on 'Details' button, the user fires the
              axios call, that allows to get the single book details by the id.
              The error generated by Book's imageLink was handled by a specific
              function that shows a default cover instead.
            </p>
            <p>
              <strong>Dependencies installed:</strong> express, axios,
              vue-router, sass
            </p>
          </div>
          <router-link to="/" exact
            ><p class="back_home">Back to BookStore</p></router-link
          >
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Specs',
}
</script>
